export class Employee {
    email: string
    name: string
    id: number
    user_id: number
    age: any
    img_path: any
    nationality: any
    total_salary: any
    basic_salary: any
    transfer_allowance: any
    housing_allowance: any
    subsistence_allowance: any
    board_number: any
    birthdate: any
    direct_action_date: any
    end_action_date: any
    end_insurance_date: any
    end_residence_date: any
    issuance_passport_date: any
    expiration_passport_date: any
    travel_date: any
    visa_number: any
    carrier_company: any
    passport_number: any
    job_number: any
    residence_number: any
    insurance_number: any
    mobility_number: any
    sick_absence_number: any
    unexcusedabsences_number: any
    actual_job: any
    visa_job: any
    gender: any
    blood_type: any
    employee_status: any
    fingerprint: any
    contract_copy: any
    passport_copy: any
    residence_copy: any
    insurance_copy: any
    employee_status_copy: any
    direct_work_copy: any
    visa_copy: any
    mobile_type: any
    kingdom_entry_port: any
    kingdom_entry_date: any
    shirt_size: any
    pants_size: any
    shoe_size: any
    created_at: any
    updated_at: any
}